name    'treydock-cron'
version '0.0.1'
source 'git://github.com/treydock/puppet-cron.git'
author 'treydock'
license 'Apache License, Version 2.0'
summary 'Puppet module to manage crond'
description 'Puppet module to manage crond and define cron jobs'
project_page 'https://github.com/treydock/puppet-cron'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
